### ISSUE TITLE
Document how to use esp8266 branch

### ISSUE THREAD

**Issue by probonopd** [igrr/Arduino#1]
Looking at the name of the branch ide-1.5.x-esp8266, I assume this is an Arduino core for the esp8266 module. It would be great if there was some documentation on how to install, compile, and use this, even if it is still a work-in-progress.

Keep up this great work, this has the potential to rock the Arduino world!

**Comment by bobricius** [comment]
hi, great job but is any way how to test in windows?

**Comment by sticilface** [comment]
Any further news? I too would be very interested to run arduino sketches. 

Some notes on howto compile? 

A
