### ISSUE TITLE
Unable to download windows 32 toolchain - Download site down?

### ISSUE THREAD

**Issue by eelcor** [igrr/Arduino#8]
Hi 

The download.igrr.me link is not working. The site seems down I am unable to build the latest version.

I'm not sure whether this is the place to report. 

Kind regards,

Eelco Rouw

**Comment by igrr** [comment]
![screen shot 2015-05-15 at 13 02 36](https://cloud.githubusercontent.com/assets/4349050/7650821/dc151452-fb02-11e4-800a-a81d9e3b1a22.png)

**Comment by eelcor** [comment]
What happened? Can I help?

**Comment by igrr** [comment]
Don't know really. Restarted the server, seems to work now...

**Comment by eelcor** [comment]
Yes! Great! Thanks for your swift response!
